# Generated by Django 4.1.3 on 2022-11-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_corn_grain_yield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=7)),
                ('max_temp_avg', models.IntegerField()),
                ('min_temp_avg', models.IntegerField()),
                ('total_precipitation', models.IntegerField()),
            ],
        ),
    ]
