# Generated by Django 4.1.3 on 2022-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dataanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysis',
            name='max_temp_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='min_temp_avg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataanalysis',
            name='total_precipitation',
            field=models.FloatField(),
        ),
    ]
